### ISSUE TITLE
Error when setting rectangular limits

### ISSUE THREAD

**Issue by JoMort** [MikkoVihtakari/ggOceanMaps#4] opened 2021-05-27 17:13 UTC
Hello, 

I am trying to set specific limits but am unable to do so. 

 ggOceanMaps::basemap(limits = 63) #Using one limit works fine

ggOceanMaps::basemap(limits = c(-27, -22, 63, 67)) # but with 4 I get an error message

Error: 
Using lon and lat as longitude and latitude columns, respectively.
projection transformed from +init=epsg:4326 to +init=epsg:3995
Error in sp::CRS(SRS_string = "EPSG:4326") : 
  no arguments in initialization list

I have also tried running the limits in the example [ggOceanMaps::basemap(limits = c(160, -160, 60, 80))] in case the problem was the area I was trying to project to, but the same error happened.

I am using up to date versions of ggplot2, sp is version 1.4-1

Please could you let me know if there is something I am doing wrong?

Thank you!!

Jo

**Comment by MikkoVihtakari** [comment] 2021-05-28 07:05
Hi Jo,

The example works on my machine. Which operating system and which version of ggOceanMaps do you have? Actually, just paste sessionInfo(). Due to the PROJ4 to PROJ6 shift, older versions of GIS packages and R do not always function together any longer. 

All the best,
-Mikko

**Comment by JoMort** [comment] 2021-05-28 07:18
Hi Mikko, 

Thanks for replying so quickly! sessionInfo() below

R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggOceanMaps_1.1 ggspatial_1.1.5 ggplot2_3.3.3  

loaded via a namespace (and not attached):
  [1] lwgeom_0.1-7          plyr_1.8.4            igraph_1.2.5          sp_1.3-1              splines_3.5.1         crosstalk_1.0.0      
  [7] leaflet_2.0.2         usethis_2.0.1         digest_0.6.20         htmltools_0.3.6       lmerTest_3.1-3        fansi_0.4.0          
 [13] magrittr_1.5          gganimate_1.0.7       CircStats_0.2-6       prettyunits_1.0.2     colorspace_1.4-1      xfun_0.9             
 [19] rgdal_1.4-4           crayon_1.3.4          lme4_1.1-27           ctmm_0.6.0            glue_1.4.2            stars_0.5-2          
 [25] gtable_0.3.0          abind_1.4-5           scales_1.0.0          mvtnorm_1.1-1         DBI_1.0.0             Rcpp_1.0.2           
 [31] viridisLite_0.3.0     xtable_1.8-4          progress_1.2.2        rWind_1.1.5           units_0.6-4           ggOceanMapsData_1.0.4
 [37] htmlwidgets_1.3       RColorBrewer_1.1-2    geosphere_1.5-10      ellipsis_0.2.0.1      pkgconfig_2.0.2       XML_3.98-1.20        
 [43] farver_2.1.0          utf8_1.1.4            rlang_0.4.11          reshape2_1.4.3        later_0.8.0           tmaptools_2.0-2      
 [49] munsell_0.5.0         tools_3.5.1           generics_0.0.2        moments_0.14          stringr_1.4.0         leafsync_0.1.0       
 [55] fs_1.3.1              purrr_0.3.2           RgoogleMaps_1.4.5.3   nlme_3.1-137          mime_0.7              compiler_3.5.1       
 [61] rstudioapi_0.10       png_0.1-7             e1071_1.7-2           tibble_2.1.3          tweenr_1.0.2          stringi_1.4.3        
 [67] gsl_2.1-6             gdistance_1.3-6       CircMLE_0.3.0         rgeos_0.5-1           lattice_0.20-41       circular_0.4-93      
 [73] Matrix_1.2-14         classInt_0.4-1        nloptr_1.2.2.1        vctrs_0.3.8           pillar_1.6.0          lifecycle_1.0.0      
 [79] cowplot_1.1.1         bitops_1.0-6          raster_3.0-2          httpuv_1.5.2          R6_2.4.0              promises_1.0.1       
 [85] KernSmooth_2.23-18    smoothr_0.2.1         codetools_0.2-18      dichromat_2.0-0       boot_1.3-27           energy_1.7-8         
 [91] MASS_7.3-53.1         assertthat_0.2.1      withr_2.1.2           parallel_3.5.1        hms_0.5.1             colortools_0.1.5     
 [97] grid_3.5.1            class_7.3-18          minqa_1.2.4           tmap_2.3              sf_0.7-7              numDeriv_2016.8-1.1  
[103] shiny_1.3.2           lubridate_1.7.10      tinytex_0.15

**Comment by MikkoVihtakari** [comment] 2021-05-28 07:54
Try updating your sp package. ggOceanMaps is moving to PROJ6 system which requires sp >= 1.4.3. See here: https://cran.r-project.org/web/packages/rgdal/vignettes/PROJ6_GDAL3.html. These two systems do not, unfortunately, work interchangeably when one wants to use advanced features such as rotating maps. There is no way around this as ggplot2 and ggspatial will do the change soon too.

If sp >= 1.4.3 is not available to R 3.5, you might have to update to >= 4.0. Please try to update sp and report back whether you'll need to update R too. I sp (>= 1.4.3) to the Imports field so a new version of the package will not work with old sp. This should fix the issue. Wondering whether I have to add R (>= 4.0.0) too. 

I am afraid that you'll need to update your R to >4.0. ggOceanMaps is moving to the new

**Comment by MikkoVihtakari** [comment] 2021-06-10 08:22
No answer...I'll close this assuming that the recipe to solve the issue is to update PROJ >= 6 and GDAL >=3. See here: https://github.com/MikkoVihtakari/ggOceanMaps/issues/2

**Closed by MikkoVihtakari** 2021-06-10 08:22 UTC
